# Generated by Django 6.0.3 on 2026-03-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='explanation',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='scenario',
            name='is_malicious',
            field=models.BooleanField(),
        ),
    ]
