# Generated by Django 6.0.3 on 2026-03-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_rename_explanation_scenario_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='is_malicious',
            field=models.BooleanField(default=True),
        ),
    ]
