# Generated by Django 6.0.3 on 2026-03-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_gameresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='image',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='title',
        ),
        migrations.AddField(
            model_name='scenario',
            name='category',
            field=models.CharField(choices=[('scam', 'Scam'), ('phishing', 'Phishing'), ('disinfo', 'Disinformation')], default='scam', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scenario',
            name='is_malicious',
            field=models.BooleanField(),
        ),
    ]
