# Generated by Django 6.0.3 on 2026-03-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_rename_description_scenario_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='explanation',
            field=models.TextField(default='No explanation provided.'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scenarios/'),
        ),
    ]
