# Generated by Django 6.0.3 on 2026-03-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_scenario_explanation_scenario_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='category',
            field=models.CharField(default='scam', max_length=10),
        ),
    ]
