# Generated by Django 6.0.3 on 2026-03-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_gameresult_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
