# Generated by Django 6.0.3 on 2026-07-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_alter_gameresult_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy (3+ obvious signs)'), ('medium', 'Medium (2 signs)'), ('hard', 'Hard (1 subtle hint)')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='scenario',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy (3+ obvious signs)'), ('medium', 'Medium (2 signs)'), ('hard', 'Hard (1 subtle hint)')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='scenario',
            name='indicators',
            field=models.JSONField(blank=True, default=list, help_text='List of specific threat signs/red flags present in this scenario.'),
        ),
    ]
